llm:
  use_emulator: false  # false = использовать OpenAI GPT-4o, true = использовать эмулятор
  fallback_to_emulator: false  # false = не переключаться на эмулятор при ошибке OpenAI
  model: 'gpt-4o'
  temperature: 0.3
  max_tokens: 4000
  max_retries: 3
  timeout: 60

# РЕЖИМ ЭМУЛЯТОРА:
# - При use_emulator: true эмулятор сначала пытается загрузить последний успешный ответ от GPT-4o
# - Файл: backend/llm/last_llm_response.json (автоматически сохраняется при каждом успешном вызове GPT-4o)
# - Это позволяет тестировать создание проектов без трат токенов
# - Если файла нет, эмулятор вернет тестовые данные по умолчанию

validation:
  required_fields:
    - 'project_analysis.project_title'
    - 'project_analysis.project_type'
    - 'project_analysis.roles'
  json_schema_strict: true
  retry_on_invalid_json: true
  max_retry_attempts: 3
