llm:
  use_emulator: false  # false = использовать OpenAI GPT-4o, true = использовать эмулятор
  model: 'gpt-4o'
  temperature: 0.3
  max_tokens: 4000
  max_retries: 3
  timeout: 60

validation:
  required_fields:
    - 'project_analysis.project_title'
    - 'project_analysis.project_type'
    - 'project_analysis.roles'
  json_schema_strict: true
  retry_on_invalid_json: true
  max_retry_attempts: 3
