# Generated by Django 4.2.24 on 2025-09-28 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание жанра')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание типа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы проектов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа роли')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание типа роли')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип роли',
                'verbose_name_plural': 'Типы ролей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('status', models.CharField(blank=True, choices=[('in_production', 'В производстве'), ('cancelled', 'Отменен или остановлен'), ('completed', 'Завершен')], max_length=20, null=True, verbose_name='Статус проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('premiere_date', models.DateField(blank=True, null=True, verbose_name='Дата премьеры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('director', models.OneToOneField(blank=True, limit_choices_to={'person_type': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_project', to='people.person', verbose_name='Режиссер')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.genre', verbose_name='Жанр')),
                ('producers', models.ManyToManyField(blank=True, limit_choices_to={'person_type': 'producer'}, related_name='produced_projects', to='people.person', verbose_name='Продюсеры')),
                ('production_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='Продюсерская компания')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projecttype', verbose_name='Тип проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание роли')),
                ('media_presence', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет'), ('doesnt_matter', 'Неважно')], max_length=20, null=True, verbose_name='Медийность')),
                ('clothing_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер одежды')),
                ('hairstyle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Прическа')),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет волос')),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет глаз')),
                ('height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Рост')),
                ('body_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телосложение')),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to='projects/roles/references/', verbose_name='Фото референс')),
                ('reference_text', models.TextField(blank=True, null=True, verbose_name='Текстовый референс')),
                ('special_conditions', models.TextField(blank=True, null=True, verbose_name='Особые условия')),
                ('audition_requirements', models.TextField(blank=True, null=True, verbose_name='Требования к пробам')),
                ('audition_text', models.TextField(blank=True, null=True, verbose_name='Текст проб текстом')),
                ('audition_files', models.FileField(blank=True, null=True, upload_to='projects/roles/auditions/', verbose_name='Текст проб файлами')),
                ('rate_per_shift', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ставка за смену')),
                ('rate_conditions', models.TextField(blank=True, null=True, verbose_name='Условия по ставке')),
                ('shooting_dates', models.TextField(blank=True, null=True, verbose_name='Даты смен')),
                ('shooting_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место съемки')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project', verbose_name='Проект')),
                ('role_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.roletype', verbose_name='Тип роли')),
            ],
            options={
                'verbose_name': 'Роль в проекте',
                'verbose_name_plural': 'Роли в проектах',
                'ordering': ['project', 'name'],
                'indexes': [models.Index(fields=['project'], name='projects_pr_project_4044af_idx'), models.Index(fields=['is_active'], name='projects_pr_is_acti_506856_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='projects_pr_is_acti_f7dee7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by'], name='projects_pr_created_c24ee1_idx'),
        ),
    ]
