# Generated by Django 4.2.24 on 2025-09-28 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('people', '0002_alter_person_person_type'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который создал этот объект', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания элемента справочника', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание элемента справочника', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли элемент справочника', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Уникальное название элемента справочника', max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления элемента справочника', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания объекта', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который создал этот объект', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание проекта', null=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='director',
            field=models.OneToOneField(blank=True, help_text='Режиссер проекта', limit_choices_to={'person_type': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_project', to='people.person', verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='project',
            name='genre',
            field=models.ForeignKey(help_text='Жанр проекта', on_delete=django.db.models.deletion.CASCADE, to='projects.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли объект в системе', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='project',
            name='premiere_date',
            field=models.DateField(blank=True, help_text='Планируемая или состоявшаяся дата премьеры', null=True, verbose_name='Дата премьеры'),
        ),
        migrations.AlterField(
            model_name='project',
            name='producers',
            field=models.ManyToManyField(blank=True, help_text='Продюсеры проекта', limit_choices_to={'person_type': 'producer'}, related_name='produced_projects', to='people.person', verbose_name='Продюсеры'),
        ),
        migrations.AlterField(
            model_name='project',
            name='production_company',
            field=models.ForeignKey(blank=True, help_text='Компания, производящая проект', null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='Продюсерская компания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(help_text='Тип проекта (фильм, сериал и т.д.)', on_delete=django.db.models.deletion.CASCADE, to='projects.projecttype', verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('in_production', 'В производстве'), ('cancelled', 'Отменен или остановлен'), ('completed', 'Завершен')], help_text='Текущий статус проекта', max_length=20, null=True, verbose_name='Статус проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Официальное название проекта', max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления объекта', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='audition_files',
            field=models.FileField(blank=True, help_text='Файлы с материалом для проб', null=True, upload_to='projects/roles/auditions/', verbose_name='Текст проб файлами'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='audition_requirements',
            field=models.TextField(blank=True, help_text='Что требуется для проб', null=True, verbose_name='Требования к пробам'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='audition_text',
            field=models.TextField(blank=True, help_text='Текстовый материал для проб', null=True, verbose_name='Текст проб текстом'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='body_type',
            field=models.CharField(blank=True, help_text='Требуемое телосложение', max_length=100, null=True, verbose_name='Телосложение'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='clothing_size',
            field=models.CharField(blank=True, help_text='Требуемый размер одежды', max_length=50, null=True, verbose_name='Размер одежды'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания объекта', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание роли', null=True, verbose_name='Описание роли'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='eye_color',
            field=models.CharField(blank=True, help_text='Требуемый цвет глаз', max_length=50, null=True, verbose_name='Цвет глаз'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='hair_color',
            field=models.CharField(blank=True, help_text='Требуемый цвет волос', max_length=50, null=True, verbose_name='Цвет волос'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='hairstyle',
            field=models.CharField(blank=True, help_text='Требуемый тип прически', max_length=100, null=True, verbose_name='Прическа'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='height',
            field=models.CharField(blank=True, help_text='Требуемый рост', max_length=50, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли объект в системе', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='media_presence',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет'), ('doesnt_matter', 'Неважно')], help_text='Требуется ли медийность для роли', max_length=20, null=True, verbose_name='Медийность'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='name',
            field=models.CharField(help_text='Название роли в проекте', max_length=255, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительные заметки по роли', null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(help_text='Проект, к которому относится роль', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='rate_conditions',
            field=models.TextField(blank=True, help_text='Дополнительные условия оплаты', null=True, verbose_name='Условия по ставке'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='rate_per_shift',
            field=models.CharField(blank=True, help_text='Ставка оплаты за смену', max_length=100, null=True, verbose_name='Ставка за смену'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='reference_photo',
            field=models.ImageField(blank=True, help_text='Референсное фото для роли', null=True, upload_to='projects/roles/references/', verbose_name='Фото референс'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='reference_text',
            field=models.TextField(blank=True, help_text='Текстовое описание референса', null=True, verbose_name='Текстовый референс'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='role_type',
            field=models.ForeignKey(blank=True, help_text='Тип роли (актер, актриса и т.д.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.roletype', verbose_name='Тип роли'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='shooting_dates',
            field=models.TextField(blank=True, help_text='Планируемые даты съемок', null=True, verbose_name='Даты смен'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='shooting_location',
            field=models.CharField(blank=True, help_text='Место проведения съемок', max_length=255, null=True, verbose_name='Место съемки'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='special_conditions',
            field=models.TextField(blank=True, help_text='Особые требования или условия для роли', null=True, verbose_name='Особые условия'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления объекта', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания элемента справочника', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание элемента справочника', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли элемент справочника', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(help_text='Уникальное название элемента справочника', max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления элемента справочника', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания элемента справочника', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание элемента справочника', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли элемент справочника', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='name',
            field=models.CharField(help_text='Уникальное название элемента справочника', max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления элемента справочника', verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='projects_ge_name_453de3_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['is_active'], name='projects_ge_is_acti_251371_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='projects_pr_project_8be368_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['genre'], name='projects_pr_genre_i_c397c6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrole',
            index=models.Index(fields=['created_by'], name='projects_pr_created_efba73_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttype',
            index=models.Index(fields=['name'], name='projects_pr_name_833023_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttype',
            index=models.Index(fields=['is_active'], name='projects_pr_is_acti_b03a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='roletype',
            index=models.Index(fields=['name'], name='projects_ro_name_b07e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='roletype',
            index=models.Index(fields=['is_active'], name='projects_ro_is_acti_caefdf_idx'),
        ),
    ]
