# Generated by Django 4.2.24 on 2025-09-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_requests', '0001_initial'),
        ('artists', '0003_alter_artist_backup_phone_alter_artist_clothing_size_and_more'),
        ('projects', '0002_projectrole_created_by_alter_genre_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type_raw',
            field=models.CharField(blank=True, help_text='Тип проекта, извлеченный LLM из текста запроса', max_length=100, null=True, verbose_name='Сырой тип проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='request',
            field=models.OneToOneField(blank=True, help_text='Запрос, на основе которого создан проект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project', to='telegram_requests.request', verbose_name='Исходный запрос'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='skills_required',
            field=models.JSONField(blank=True, default=list, help_text='Навыки, требуемые для роли (JSON массив)', null=True, verbose_name='Требуемые навыки'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='suggested_artists',
            field=models.ManyToManyField(blank=True, help_text='Артисты, предложенные LLM для этой роли', related_name='suggested_roles', to='artists.artist', verbose_name='Предложенные артисты'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['request'], name='projects_pr_request_1042a7_idx'),
        ),
    ]
