# Generated by Django 4.2.24 on 2025-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_type_raw_project_request_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='projects_pr_title_ba614c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['description'], name='projects_pr_descrip_f7f88c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'status'], name='projects_pr_is_acti_189799_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title', 'is_active'], name='projects_pr_title_45c34e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type', 'is_active'], name='projects_pr_project_aa23e1_idx'),
        ),
    ]
