# Generated by Django 4.2.24 on 2025-10-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('boy', 'Мальчик'), ('girl', 'Девочка'), ('doesnt_matter', 'Не важно')], help_text='Требуемый пол для роли', max_length=20, null=True, verbose_name='Пол'),
        ),
    ]
