# Generated by Django 4.2.24 on 2025-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectrole_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='age_max',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальный требуемый возраст для роли', null=True, verbose_name='Максимальный возраст'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='age_min',
            field=models.PositiveIntegerField(blank=True, help_text='Минимальный требуемый возраст для роли', null=True, verbose_name='Минимальный возраст'),
        ),
    ]
