# Generated by Django 4.2.24 on 2025-10-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectrole_age_max_projectrole_age_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название элемента справочника', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание элемента справочника', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли элемент справочника', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания элемента справочника', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления элемента справочника', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Размер обуви',
                'verbose_name_plural': 'Размеры обуви',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='projects_sh_name_4afc4d_idx'), models.Index(fields=['is_active'], name='projects_sh_is_acti_16627d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название элемента справочника', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание элемента справочника', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли элемент справочника', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания элемента справочника', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления элемента справочника', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Национальность',
                'verbose_name_plural': 'Национальности',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='projects_na_name_a67042_idx'), models.Index(fields=['is_active'], name='projects_na_is_acti_24b0e1_idx')],
            },
        ),
        migrations.AddField(
            model_name='projectrole',
            name='nationality',
            field=models.ForeignKey(blank=True, help_text='Требуемая национальность для роли', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.nationality', verbose_name='Национальность'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='shoe_size',
            field=models.ForeignKey(blank=True, help_text='Требуемый размер обуви', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.shoesize', verbose_name='Размер обуви'),
        ),
    ]
