# Generated by Django 4.2.24 on 2025-10-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_add_search_indexes'),
        ('projects', '0007_shoesize_nationality_projectrole_nationality_and_more'),
    ]

    operations = [
        # casting_director уже существует, удалена операция AddField
        migrations.AlterField(
            model_name='project',
            name='director',
            field=models.ForeignKey(blank=True, help_text='Режиссер проекта', limit_choices_to={'person_type': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_projects', to='people.person', verbose_name='Режиссер'),
        ),
    ]
