# Generated by Django 4.2.24 on 2025-10-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_importsession'),
        ('projects', '0009_add_casting_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='casting_director',
            field=models.ForeignKey(blank=True, help_text='Кастинг-директор проекта', limit_choices_to={'person_type': 'casting_director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_projects', to='people.person', verbose_name='Кастинг-директор'),
        ),
        migrations.AlterField(
            model_name='project',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='Жанр проекта', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, help_text='Тип проекта (фильм, сериал и т.д.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projecttype', verbose_name='Тип проекта'),
        ),
    ]
