# Generated by Django 4.2.24 on 2025-10-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_casting_director_alter_project_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='usage_rights_parsed',
            field=models.JSONField(blank=True, default=None, help_text='Структурированная информация о правах для рекламы: {raw_text, types, duration, territory}', null=True, verbose_name='Права использования'),
        ),
    ]
