# Generated by Django 4.2.24 on 2025-09-28 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('director', 'Режиссер'), ('producer', 'Продюсер')], max_length=20, verbose_name='Тип персоны')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/photos/', verbose_name='Фотография')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Национальность')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Личный сайт')),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram')),
                ('kinopoisk_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Кинотеатр')),
                ('social_media', models.JSONField(blank=True, default=dict, null=True, verbose_name='Социальные сети')),
                ('awards', models.TextField(blank=True, null=True, verbose_name='Награды и достижения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_people', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['person_type'], name='people_pers_person__8bb150_idx'), models.Index(fields=['is_active'], name='people_pers_is_acti_c9fc80_idx'), models.Index(fields=['created_by'], name='people_pers_created_5acd02_idx')],
            },
        ),
    ]
