# Generated by Django 4.2.24 on 2025-09-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('director', 'Режиссер'), ('producer', 'Продюсер'), ('casting_director', 'Кастинг-директор')], max_length=20, verbose_name='Тип персоны'),
        ),
    ]
