# Generated by Django 4.2.24 on 2025-10-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_person_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='people_pers_email_52ffb2_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['phone'], name='people_pers_phone_b55729_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['telegram_username'], name='people_pers_telegra_6266fb_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name'], name='people_pers_first_n_4becf6_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name'], name='people_pers_last_na_f433f3_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['person_type', 'is_active'], name='people_pers_person__5a9977_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name'], name='people_pers_first_n_7e848a_idx'),
        ),
    ]
