# Generated by Django 4.2.24 on 2025-10-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_add_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя'),
        ),
    ]
