# Generated by Django 4.2.24 on 2025-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_make_first_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='emails',
            field=models.JSONField(blank=True, default=list, help_text='Массив email (максимум 5)', verbose_name='Email адреса'),
        ),
        migrations.AddField(
            model_name='person',
            name='phones',
            field=models.JSONField(blank=True, default=list, help_text='Массив телефонов (максимум 5)', verbose_name='Телефоны'),
        ),
        migrations.AddField(
            model_name='person',
            name='telegram_usernames',
            field=models.JSONField(blank=True, default=list, help_text='Массив Telegram username (максимум 5)', verbose_name='Telegram аккаунты'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram (устаревшее)'),
        ),
    ]
