# Generated by Django 4.2.24 on 2025-10-16 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_requests', '0006_simplify_request_statuses'),
        ('people', '0006_migrate_contacts_to_arrays'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonContactAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=20, verbose_name='Тип контакта')),
                ('contact_value', models.CharField(max_length=255, verbose_name='Значение контакта')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Отклонено')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('added_from_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_contact_additions', to='telegram_requests.request', verbose_name='Добавлен из запроса')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_additions', to='people.person', verbose_name='Персона')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contact_additions', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Добавление контакта персоны',
                'verbose_name_plural': 'Добавления контактов персон',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['person', 'is_confirmed'], name='people_pers_person__b2de65_idx'), models.Index(fields=['added_at'], name='people_pers_added_a_b1b2dc_idx'), models.Index(fields=['is_confirmed', 'is_rejected'], name='people_pers_is_conf_12fbc0_idx')],
            },
        ),
    ]
