# Generated by Django 4.2.24 on 2025-10-17 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0007_add_person_contact_addition_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='imports/people/', verbose_name='Файл импорта')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processing', 'Обработка'), ('pending', 'Ожидает подтверждения'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('records_data', models.JSONField(blank=True, default=dict, help_text='Хранение обработанных записей из файла', verbose_name='Данные записей')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Всего строк')),
                ('valid_rows', models.IntegerField(default=0, verbose_name='Валидных строк')),
                ('invalid_rows', models.IntegerField(default=0, verbose_name='Невалидных строк')),
                ('created_count', models.IntegerField(default=0, verbose_name='Создано персон')),
                ('updated_count', models.IntegerField(default=0, verbose_name='Обновлено персон')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Пропущено')),
                ('error_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия импорта персон',
                'verbose_name_plural': 'Сессии импорта персон',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='people_impo_user_id_8c3536_idx'), models.Index(fields=['created_at'], name='people_impo_created_024140_idx'), models.Index(fields=['status'], name='people_impo_status_053923_idx')],
            },
        ),
    ]
