# Generated by Django 4.2.24 on 2025-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_backup_phone_alter_artist_clothing_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='backup_phone',
            field=models.CharField(blank=True, help_text='Запасной номер телефона артиста', max_length=20, null=True, verbose_name='Запасной телефон'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='clothing_size',
            field=models.CharField(blank=True, help_text='Размер одежды артиста', max_length=20, null=True, verbose_name='Размер одежды'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.CharField(blank=True, help_text='Основной номер телефона артиста', max_length=20, null=True, verbose_name='Основной телефон'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='shoe_size',
            field=models.CharField(blank=True, help_text='Размер обуви артиста', max_length=20, null=True, verbose_name='Размер обуви'),
        ),
    ]
