# Generated by Django 4.2.24 on 2025-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_backup_phone_alter_artist_clothing_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='rate_per_day',
        ),
        migrations.AddField(
            model_name='artist',
            name='busy_dates',
            field=models.JSONField(blank=True, default=list, help_text="Массив занятых дат артиста в формате ['YYYY-MM-DD', ...]", verbose_name='Занятые даты'),
        ),
        migrations.AddField(
            model_name='artist',
            name='rate_per_shift',
            field=models.CharField(blank=True, help_text='Ставка оплаты за смену', max_length=100, null=True, verbose_name='Ставка за смену'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('boy', 'Мальчик'), ('girl', 'Девочка'), ('doesnt_matter', 'Не важно')], help_text='Пол артиста', max_length=20, verbose_name='Пол'),
        ),
    ]
