# Generated by Django 4.2.24 on 2025-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_remove_artist_rate_per_day_artist_busy_dates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistskill',
            options={'ordering': ['skill__name'], 'verbose_name': 'Навык артиста', 'verbose_name_plural': 'Навыки артистов'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Название навыка', max_length=100, unique=True, verbose_name='Название навыка'),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_group',
        ),
        migrations.DeleteModel(
            name='SkillGroup',
        ),
    ]
