# Docker Compose override для локальной разработки
# Использование: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Django Backend - с hot reload через runserver
  backend:
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    volumes:
      - ../backend:/app
      - media_files:/app/media
      - static_files:/app/staticfiles
    # В dev режиме используем разработческий Dockerfile
    build:
      context: ../backend
      dockerfile: Dockerfile

  # Frontend - с Vite HMR и polling для Docker
  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      # Маппим исходники для hot reload
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
      - ../frontend/index.html:/app/index.html
      - ../frontend/vite.config.ts:/app/vite.config.ts
      - ../frontend/tsconfig.json:/app/tsconfig.json
      - ../frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ../frontend/tsconfig.node.json:/app/tsconfig.node.json
      # Анонимный volume для node_modules (не переписываем с хоста)
      - /app/node_modules
    # В dev режиме используем разработческий Dockerfile
    build:
      context: ../frontend
      dockerfile: Dockerfile

