# Generated by Django 4.2.24 on 2025-09-28 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Официальное название кинокомпании', max_length=200, verbose_name='Название компании')),
                ('company_type', models.CharField(choices=[('production', 'Кинопроизводство'), ('distribution', 'Дистрибуция'), ('studio', 'Студия'), ('network', 'Телесеть'), ('streaming', 'Стриминг-платформа'), ('other', 'Другое')], default='production', help_text='Основной тип деятельности компании', max_length=20, verbose_name='Тип компании')),
                ('description', models.TextField(blank=True, help_text='Подробное описание компании', null=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, help_text='Логотип компании', null=True, upload_to='companies/logos/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, help_text='Официальный сайт компании', null=True, verbose_name='Веб-сайт')),
                ('email', models.EmailField(blank=True, help_text='Контактный email', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Контактный телефон', max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, help_text='Физический адрес компании', null=True, verbose_name='Адрес')),
                ('founded_year', models.PositiveIntegerField(blank=True, help_text='Год основания компании', null=True, verbose_name='Год основания')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли компания', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, help_text='Агент, который добавил компанию', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано агентом')),
            ],
            options={
                'verbose_name': 'Кинокомпания',
                'verbose_name_plural': 'Кинокомпании',
                'ordering': ['name'],
            },
        ),
    ]
