# Generated by Django 4.2.24 on 2025-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_by'], name='companies_c_created_1d640c_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_type'], name='companies_c_company_bf414f_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_c_name_2d8260_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['website'], name='companies_c_website_8c119e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['email'], name='companies_c_email_aa1293_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'company_type'], name='companies_c_is_acti_d8a8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name', 'is_active'], name='companies_c_name_288412_idx'),
        ),
    ]
