# Generated by Django 4.2.24 on 2025-09-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_type_raw_project_request_and_more'),
        ('telegram_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='analysis_status',
            field=models.CharField(choices=[('new', 'Новый'), ('analyzed', 'Проанализирован'), ('processed', 'Обработан')], default='new', help_text='Статус анализа запроса через LLM', max_length=20, verbose_name='Статус анализа'),
        ),
        migrations.AddField(
            model_name='request',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект, созданный на основе этого запроса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['analysis_status'], name='telegram_re_analysi_fcc65c_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['project'], name='telegram_re_project_d47d26_idx'),
        ),
    ]
