# Generated by Django 4.2.24 on 2025-09-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_type_raw_project_request_and_more'),
        ('telegram_requests', '0002_request_analysis_status_request_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект, созданный на основе этого запроса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='projects.project', verbose_name='Проект'),
        ),
    ]
