# Generated by Django 4.2.24 on 2025-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_requests', '0003_alter_request_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Миниатюра изображения для быстрой загрузки', null=True, upload_to='requests/thumbnails/%Y/%m/%d/', verbose_name='Миниатюра'),
        ),
    ]
