# Generated by Django 4.2.24 on 2025-10-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_requests', '0004_requestimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='author_username',
            field=models.CharField(blank=True, help_text='Username автора в Telegram (например, @username)', max_length=100, null=True, verbose_name='Telegram username автора'),
        ),
    ]
