# Generated by Django 4.2.24 on 2025-10-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_requests', '0005_request_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Новый'), ('completed', 'Обработан')], default='pending', help_text='Текущий статус обработки запроса', max_length=20, verbose_name='Статус'),
        ),
    ]
