# Generated by Django 4.2.24 on 2025-10-18 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20251005_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор бэкапа', primary_key=True, serialize=False, verbose_name='ID бэкапа')),
                ('filename', models.CharField(help_text='Имя файла бэкапа', max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Размер файла бэкапа в байтах', null=True, verbose_name='Размер файла (байт)')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('deleted', 'Удален')], default='pending', help_text='Текущий статус бэкапа', max_length=20, verbose_name='Статус')),
                ('google_drive_file_id', models.CharField(blank=True, help_text='Идентификатор файла в Google Drive', max_length=255, null=True, verbose_name='ID файла в Google Drive')),
                ('google_drive_url', models.URLField(blank=True, help_text='Прямая ссылка на файл в Google Drive', null=True, verbose_name='Ссылка на файл в Google Drive')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания бэкапа', verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Дата и время завершения создания бэкапа', null=True, verbose_name='Дата завершения')),
                ('error_message', models.TextField(blank=True, help_text='Текст ошибки, если бэкап не удался', null=True, verbose_name='Сообщение об ошибке')),
                ('created_by', models.ForeignKey(blank=True, help_text='Пользователь, который создал бэкап', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Запись о бэкапе',
                'verbose_name_plural': 'Записи о бэкапах',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_backup_status_972427_idx'), models.Index(fields=['created_at'], name='core_backup_created_54ed6e_idx'), models.Index(fields=['created_by'], name='core_backup_created_ee6366_idx')],
            },
        ),
    ]
